//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by rsrc.rc
//
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 1
#define RT_MANIFEST                     24
#define IDD_DIALOG1                     101
#define IDR_MENU1                       102
#define IDD_DIALOG2                     104
#define IDC_CURSOR1                     105
#define IDI_ICON1                       106
#define IDR_ACCELERATOR1                107
#define IDI_ICON2                       115
#define CONTROL_PANEL_RESOURCE_ID       123
#define IDC_LIST1                       1000
#define IDC_STATUSBAR                   1001
#define IDC_EDIT1                       1002
#define IDC_TREE1                       1003
#define IDM_CREATEVIEWOBJECT            40960
#define IDM_BINDTOOBJECT                40961
#define IDM_GETUIOBJECTOF               40962
#define IDM_OPENNEWWND                  40963
#define IDM_STATUSLINE                  40964
#define IDM_ABOUT                       40965
#define IDM_COMPMENUS                   40966
#define IDM_REFRESH                     40967
#define IDM_EXIT                        40968
#define IDM_SORT                        40969
#define IDM_DROPTARGET                  40970
#define IDM_TRACKSELECT                 40971
#define IDM_DDERESPOND                  40972
#define IDM_BROWSEFILES                 40973
#define IDM_DELETE                      40974
#define IDM_EXPAND                      40975  

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40976
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
